# Generated by Django 5.2.17 on 2026-09-16 23:36

from django.db import migrations, models

# informa que a tabela "usuario" ja existe no banco de dados e nao deve ser gerenciada pelo Django, evitando criacoes ou alteracoes da tabela durante as migracoes
class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(db_column='senha', max_length=255)),
                ('primeiro_acesso', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
